<?php $__env->startSection('content'); ?>
<div class="page-head"><div><div class="eyebrow">ACCESS CONTROL</div><h1>User Management</h1><p class="muted">Create staff accounts and assign roles.</p></div><a class="primary" href="<?php echo e(route('users.create')); ?>">+ Add User</a></div>
<div class="glass table-card"><div class="table-wrap"><table><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($user->name); ?></strong></td><td><?php echo e($user->email); ?></td><td><span class="pill"><?php echo e(optional($user->roleModel)->name ?? ucfirst($user->role)); ?></span></td><td><span class="status <?php echo e($user->active?'ok':'off'); ?>"><?php echo e($user->active?'Active':'Inactive'); ?></span></td><td class="actions"><a class="secondary" href="<?php echo e(route('users.edit',$user)); ?>">Edit</a><form method="post" action="<?php echo e(route('users.destroy',$user)); ?>" onsubmit="return confirm('Delete this user?')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="danger">Delete</button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="5" class="empty">No users found.</td></tr><?php endif; ?>
</tbody></table></div></div>
<div class="page-head compact"><div><div class="eyebrow">ROLES</div><h2>Roles & Permissions</h2></div><a class="secondary" href="<?php echo e(route('roles.index')); ?>">Manage Roles</a></div>
<div class="role-grid"><?php $__currentLoopData = $roles; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $role): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="glass mini-card"><div class="role-title"><strong><?php echo e($role->name); ?></strong><span class="pill"><?php echo e($role->users()->count()); ?> users</span></div><p class="muted"><?php echo e($role->description ?: 'Access profile'); ?></p><div class="chips"><?php $__currentLoopData = $role->permissions->take(5); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $p): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><span><?php echo e($p->name); ?></span><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?> <?php if($role->permissions->count()>5): ?><span>+<?php echo e($role->permissions->count()-5); ?> more</span><?php endif; ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\retail-pos-full\resources\views/users/index.blade.php ENDPATH**/ ?>